#!/usr/bin/env bash
set -euo pipefail

# install.sh -- install the AltGr Symbols XKB layouts without xkalamine.
#
# Replicates what `sudo xkalamine install us.toml ru.toml` does, but works on
# the prebuilt files in dist/ so no Python / kalamine is required:
#
#   - merges the `xkb_symbols "sym"` block into symbols/{us,ru}
#     (wrapped in // KALAMINE::SYM::BEGIN/END markers, same as xkalamine,
#      so an existing kalamine install is replaced and stays removable)
#   - registers the `sym` variant in rules/{base,evdev}.{xml,lst}
#   - on Wayland without root access falls back to ~/.config/xkb (user-space)

VARIANT="sym"
US_LAYOUT="us"
RU_LAYOUT="ru"
US_DESC="QWERTY SYM"
RU_DESC="ЙЦУКЕНГ SYM"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST="$SCRIPT_DIR/dist"
US_SYMBOLS="$DIST/us-sym.xkb_symbols"
RU_SYMBOLS="$DIST/ru-sym.xkb_symbols"
US_KEYLAYOUT="$DIST/us-sym.keylayout"
RU_KEYLAYOUT="$DIST/ru-sym.keylayout"

MARKER_BEGIN="// KALAMINE::${VARIANT^^}::BEGIN"
MARKER_END="// KALAMINE::${VARIANT^^}::END"

die() {
  echo "install.sh: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: install.sh [COMMAND]

Install or remove the AltGr Symbols XKB layouts (us/ru) without xkalamine.

Commands:
  install   (default) install the layouts into the XKB config
  remove    uninstall the layouts from the XKB config
  help      show this help
EOF
}

require_prebuilt() {
  [ -f "$US_SYMBOLS" ] || die "missing $US_SYMBOLS (run ./build.sh first)"
  [ -f "$RU_SYMBOLS" ] || die "missing $RU_SYMBOLS (run ./build.sh first)"
}

# Which XKB root to use: system-wide, Wayland user-space, or fail.
detect_xkb_dir() {
  if [ -w "${XKB_CONFIG_ROOT:-/usr/share/X11/xkb}" ]; then
    echo "system"
  elif [ -z "${SUDO_UID:-}" ] && [ -n "${WAYLAND_DISPLAY:-}" ]; then
    echo "user"
  else
    echo "none"
  fi
}

# Extract the `xkb_symbols "sym"` block (from `partial …` to the closing `};`).
extract_block() {
  sed -n '/^partial /,/^};$/p' "$1"
}

# Wrap the block in kalamine-compatible markers.
make_marker_block() {
  printf '%s\n%s\n%s\n' \
    "$MARKER_BEGIN" "$(extract_block "$1")" "$MARKER_END"
}

xml_variant_block() {
  printf '        <variant>\n          <configItem>\n            <name>%s</name>\n            <description>%s</description>\n          </configItem>\n        </variant>\n' \
    "$VARIANT" "$1"
}

lst_line() {
  printf '  %-15s%s: %s\n' "$VARIANT" "$1" "$2"
}

# Merge `block` into a symbols file (create it if missing, replace any
# previous kalamine block), idempotent.
symbols_update() {
  local file="$1" block="$2"
  local tmp="${file}.tmp"
  mkdir -p "$(dirname "$file")"
  if [ -f "$file" ]; then
    awk -v beg="$MARKER_BEGIN" -v end="$MARKER_END" '
      $0 == beg { skip = 1; next }
      $0 == end { skip = 0; next }
      !skip     { print }
    ' "$file" >"$tmp"
    printf '\n%s\n' "$block" >>"$tmp"
  else
    {
      printf '// Generated by install.sh on %s\n' "$(date +%F)"
      printf '\n%s\n' "$block"
    } >"$tmp"
  fi
  mv -f "$tmp" "$file"
}

# Strip the previous kalamine block from a symbols file, if any.
remove_symbols() {
  local xkb="$1" file tmp
  for file in "$xkb/symbols/$US_LAYOUT" "$xkb/symbols/$RU_LAYOUT"; do
    [ -f "$file" ] || continue
    tmp="${file}.tmp"
    if ! awk -v beg="$MARKER_BEGIN" -v end="$MARKER_END" '
      $0 == beg { skip = 1; next }
      $0 == end { skip = 0; next }
      !skip     { print }
    ' "$file" >"$tmp"; then
      rm -f "$tmp"
      die "failed to update $file"
    fi
    # leave real layout files intact, but drop leftover stub files that
    # would otherwise shadow the system layout on Wayland
    if grep -q '^xkb_symbols\|^partial' "$tmp"; then
      mv -f "$tmp" "$file"
    else
      rm -f "$tmp" "$file"
    fi
  done
}

# Insert / refresh the <variant> for a layout in a rules XML file.
xml_update() {
  local file="$1" layout="$2" vblock="$3"
  if ! TARGET="$layout" HANDLE="$VARIANT" VBLOCK="$vblock" awk '
    BEGIN {
      target = ENVIRON["TARGET"]
      handle = ENVIRON["HANDLE"]
      vblock = ENVIRON["VBLOCK"]
      in_layout = 0; got_name = 0; layout = ""
      in_variant = 0; keep = 0; n = 0; inserted = 0; found = 0
    }
    function name_of(line,    s) {
      if (match(line, /<name>[^<]+<\/name>/)) {
        s = substr(line, RSTART, RLENGTH)
        gsub(/<[^>]+>/, "", s)
        return s
      }
      return ""
    }
    function emit_variant(    m, i) {
      m = split(vblock, a, "\n")
      for (i = 1; i <= m; i++) print a[i]
    }
    {
      if ($0 ~ /<layout>/) {
        in_layout = 1; got_name = 0; layout = ""
        in_variant = 0
        print
        next
      }
      if (in_layout && $0 ~ /<\/layout>/) {
        if (layout == target) {
          found = 1
          if (!inserted) {
            print "      <variantList>"
            emit_variant()
            print "      </variantList>"
            inserted = 1
          }
        }
        in_layout = 0
        print
        next
      }
      if (in_layout) {
        if (!got_name) {
          s = name_of($0)
          if (s != "") { layout = s; got_name = 1 }
        }
        if (layout == target) {
          if ($0 ~ /<variant>/) { in_variant = 1; keep = 1; n = 0 }
          if (in_variant) {
            buf[++n] = $0
            s = name_of($0)
            if (s == handle) keep = 0
            if ($0 ~ /<\/variant>/) {
              if (keep) for (i = 1; i <= n; i++) print buf[i]
              in_variant = 0
            }
            next
          }
          if ($0 ~ /<\/variantList>/) {
            emit_variant()
            inserted = 1
          }
          print
          next
        }
      }
      print
    }
    END {
      if (!found) {
        print "error: XKB layout \"" target "\" not defined in " FILENAME > "/dev/stderr"
        exit 1
      }
    }
  ' "$file" >"$file.tmp"; then
    rm -f "$file.tmp"
    die "failed to update $file"
  fi
  mv -f "$file.tmp" "$file"
}

# Remove the <variant> for a layout from a rules XML file.
xml_remove() {
  local file="$1" layout="$2"
  if ! TARGET="$layout" HANDLE="$VARIANT" awk '
    BEGIN {
      target = ENVIRON["TARGET"]
      handle = ENVIRON["HANDLE"]
      in_layout = 0; got_name = 0; layout = ""
      in_variant = 0; keep = 0; n = 0
    }
    function name_of(line,    s) {
      if (match(line, /<name>[^<]+<\/name>/)) {
        s = substr(line, RSTART, RLENGTH)
        gsub(/<[^>]+>/, "", s)
        return s
      }
      return ""
    }
    {
      if ($0 ~ /<layout>/) {
        in_layout = 1; got_name = 0; layout = ""
        in_variant = 0
        print
        next
      }
      if (in_layout && $0 ~ /<\/layout>/) {
        in_layout = 0
        print
        next
      }
      if (in_layout) {
        if (!got_name) {
          s = name_of($0)
          if (s != "") { layout = s; got_name = 1 }
        }
        if (layout == target) {
          if ($0 ~ /<variant>/) { in_variant = 1; keep = 1; n = 0 }
          if (in_variant) {
            buf[++n] = $0
            s = name_of($0)
            if (s == handle) keep = 0
            if ($0 ~ /<\/variant>/) {
              if (keep) for (i = 1; i <= n; i++) print buf[i]
              in_variant = 0
            }
            next
          }
        }
      }
      print
    }
  ' "$file" >"$file.tmp"; then
    rm -f "$file.tmp"
    die "failed to update $file"
  fi
  mv -f "$file.tmp" "$file"
}

# Add a `variant layout: description` line to the `! variant` section (idempotent).
lst_update() {
  local file="$1" layout="$2" line="$3"
  if ! TARGET="$layout" HANDLE="$VARIANT" LSTLINE="$line" awk '
    BEGIN {
      target = ENVIRON["TARGET"]
      handle = ENVIRON["HANDLE"]
      line = ENVIRON["LSTLINE"]
      pat = "^[ \t]*" handle "[ \t]+" target ":"
      in_sec = 0; done = 0
    }
    /^! variant[ \t]*$/ { in_sec = 1; done = 0; print; next }
    in_sec && /^! / {
      if (!done) { print line; done = 1 }
      in_sec = 0
    }
    in_sec && $0 ~ pat { next }
    { print }
    END { if (in_sec && !done) print line }
  ' "$file" >"$file.tmp"; then
    rm -f "$file.tmp"
    die "failed to update $file"
  fi
  mv -f "$file.tmp" "$file"
}

# Drop the `variant layout:` line from the `! variant` section.
lst_remove() {
  local file="$1" layout="$2"
  if ! TARGET="$layout" HANDLE="$VARIANT" awk '
    BEGIN {
      target = ENVIRON["TARGET"]
      handle = ENVIRON["HANDLE"]
      pat = "^[ \t]*" handle "[ \t]+" target ":"
      in_sec = 0
    }
    /^! variant[ \t]*$/ { in_sec = 1; print; next }
    in_sec && /^! / { in_sec = 0 }
    in_sec && $0 ~ pat { next }
    { print }
  ' "$file" >"$file.tmp"; then
    rm -f "$file.tmp"
    die "failed to update $file"
  fi
  mv -f "$file.tmp" "$file"
}

# Merge the symbol blocks into $xkb/symbols/{us,ru}.
install_symbols() {
  local xkb="$1"
  mkdir -p "$xkb/symbols"
  symbols_update "$xkb/symbols/$US_LAYOUT" "$(make_marker_block "$US_SYMBOLS")"
  symbols_update "$xkb/symbols/$RU_LAYOUT" "$(make_marker_block "$RU_SYMBOLS")"
}

# Write a self-contained user-space rules dir: include chain + our layouts.
write_user_rules() {
  local xkb="$1"
  if [ ! -f "$xkb/rules/evdev" ]; then
    printf '! include %%S/evdev\n' >"$xkb/rules/evdev"
  fi
  cat >"$xkb/rules/evdev.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">
<!-- Generated by install.sh on $(date +%F) -->
<xkbConfigRegistry version="1.1">
  <layoutList>
    <layout>
      <configItem>
        <name>us</name>
        <shortDescription>en</shortDescription>
        <description>English</description>
        <languageList>
          <iso639Id>eng</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>sym</name>
            <description>QWERTY SYM</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
    <layout>
      <configItem>
        <name>ru</name>
        <shortDescription>ru</shortDescription>
        <description>Russian</description>
        <languageList>
          <iso639Id>rus</iso639Id>
        </languageList>
      </configItem>
      <variantList>
        <variant>
          <configItem>
            <name>sym</name>
            <description>ЙЦУКЕНГ SYM</description>
          </configItem>
        </variant>
      </variantList>
    </layout>
  </layoutList>
</xkbConfigRegistry>
EOF
  {
    printf '! model\n! layout\n'
    printf '  %-15s%s\n' "$US_LAYOUT" "English"
    printf '  %-15s%s\n' "$RU_LAYOUT" "Russian"
    printf '! variant\n'
    lst_line "$US_LAYOUT" "$US_DESC"
    lst_line "$RU_LAYOUT" "$RU_DESC"
    printf '! option\n'
  } >"$xkb/rules/evdev.lst"
}

install_linux_system() {
  local xkb="${XKB_CONFIG_ROOT:-/usr/share/X11/xkb}" f
  install_symbols "$xkb"
  for f in "$xkb/rules/base.xml" "$xkb/rules/evdev.xml"; do
    [ -f "$f" ] || continue
    xml_update "$f" "$US_LAYOUT" "$(xml_variant_block "$US_DESC")"
    xml_update "$f" "$RU_LAYOUT" "$(xml_variant_block "$RU_DESC")"
  done
  for f in "$xkb/rules/base.lst" "$xkb/rules/evdev.lst"; do
    [ -f "$f" ] || continue
    lst_update "$f" "$US_LAYOUT" "$(lst_line "$US_LAYOUT" "$US_DESC")"
    lst_update "$f" "$RU_LAYOUT" "$(lst_line "$RU_LAYOUT" "$RU_DESC")"
  done
  echo "Installed system-wide into $xkb."
  echo
  echo "Activate now (X11):"
  echo "  setxkbmap $US_LAYOUT -variant $VARIANT"
  echo "  setxkbmap $RU_LAYOUT -variant $VARIANT"
  echo "Or pick 'English (QWERTY SYM)' / 'Russian (ЙЦУКЕНГ SYM)' in keyboard settings."
}

install_linux_user() {
  local xkb="${XDG_CONFIG_HOME:-$HOME/.config}/xkb"
  mkdir -p "$xkb/symbols" "$xkb/rules"
  write_user_rules "$xkb"
  install_symbols "$xkb"
  echo "Installed into $xkb (Wayland user-space)."
  echo
  echo "The layouts should appear in your compositor's keyboard settings."
  echo "For sway/hyprland you can set, for example:"
  echo "  input type:keyboard {"
  echo "      xkb_layout \"$US_LAYOUT\""
  echo "      xkb_variant \"$VARIANT\""
  echo "  }"
}

linux_install() {
  local mode
  mode="$(detect_xkb_dir)"
  case "$mode" in
    system) install_linux_system ;;
    user) install_linux_user ;;
    *) die "no writable XKB config found; run as root: sudo env PATH=\$PATH $0 install" ;;
  esac
}

linux_remove_system() {
  local xkb="${XKB_CONFIG_ROOT:-/usr/share/X11/xkb}" f
  remove_symbols "$xkb"
  for f in "$xkb/rules/base.xml" "$xkb/rules/evdev.xml"; do
    [ -f "$f" ] || continue
    xml_remove "$f" "$US_LAYOUT"
    xml_remove "$f" "$RU_LAYOUT"
  done
  for f in "$xkb/rules/base.lst" "$xkb/rules/evdev.lst"; do
    [ -f "$f" ] || continue
    lst_remove "$f" "$US_LAYOUT"
    lst_remove "$f" "$RU_LAYOUT"
  done
  echo "Removed from $xkb."
}

linux_remove_user() {
  local xkb="${XDG_CONFIG_HOME:-$HOME/.config}/xkb"
  rm -f "$xkb/rules/evdev.xml" "$xkb/rules/evdev.lst"
  remove_symbols "$xkb"
  echo "Removed from $xkb."
}

linux_remove() {
  local mode
  mode="$(detect_xkb_dir)"
  case "$mode" in
    system) linux_remove_system ;;
    user) linux_remove_user ;;
    *) die "no writable XKB config found; run as root: sudo env PATH=\$PATH $0 remove" ;;
  esac
}

darwin_install() {
  local dest="$HOME/Library/Keyboard Layouts"
  [ -f "$US_KEYLAYOUT" ] || die "missing $US_KEYLAYOUT (run ./build.sh first)"
  [ -f "$RU_KEYLAYOUT" ] || die "missing $RU_KEYLAYOUT (run ./build.sh first)"
  mkdir -p "$dest"
  cp "$US_KEYLAYOUT" "$dest/"
  cp "$RU_KEYLAYOUT" "$dest/"
  echo "Layouts copied to $dest."
  echo "Log out (or reboot), then add them via"
  echo "System Settings -> Keyboard -> Input Sources -> '+'."
}

main() {
  local cmd="${1:-install}"
  case "$cmd" in
    install) require_prebuilt ;;
    remove) ;;
    help | -h | --help) usage
      return 0 ;;
    *) usage >&2
      exit 1 ;;
  esac
  case "$(uname -s)" in
    Linux)
      if [ "$cmd" = install ]; then
        linux_install
      else
        linux_remove
      fi
      ;;
    Darwin)
      [ "$cmd" = remove ] && die "nothing to remove on macOS; delete the .keylayout files manually"
      darwin_install
      ;;
    *)
      die "unsupported OS: $(uname -s)"
      ;;
  esac
}

main "$@"